# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b390bebc60ef7abf58e53c41afbdf96cfda37ce43d62386b99b1b3acfd542c7ed8c144c58eb8423955842db29e789cda399ab88823b88ec2fe7be328e555da52
  google_client_id: 472184425285-civnsvqk2kb97kl9ctsrirkeo130d42m.apps.googleusercontent.com

  google_client_secret: zNhzPRKJNe42BVtpjmah3ceu

test:
  secret_key_base: 21b58d8ecb698fb6856425d6d1210c5c0c15561e256b1479b452941255d9998f39ecdd9c242532c1c2a22d4f3671944d2bbb15979968c5f30c11a8220a30dd72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
