production: &production
  :url: redis://spelackec-001.apvows.0001.apne1.cache.amazonaws.com:6379
  :host: localhost
  :port: 6379
  :timeout: 1
staging: &staging
  :url: redis://spelackec-001.apvows.0001.apne1.cache.amazonaws.com:6379
  :host: localhost
  :port: 6379
  :timeout: 1
local: &local
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true
development: *local
test: *local
